export default {
	loginGoodPayload: { email: 'test1@test.com', password: '123321' },
	loginBadPayload: { email: 'test1test.com' },
	sinupGoodPayload: {
		first_name: 'bruce',
		last_name: 'joe',
		role: 'Employee',
		password: 'Hello123321+_',
		passwordConfirmation: 'Hello123321+_+',
		email: 'test20@test.com',
	},
	sinupBadPayload: {
		first_name: 'bruce',
		last_name: 'joe',
		role: 'Employee',
		password: 'Hello123321+_',
		passwordConfirmation: 'Hello123321+_+-',
		email: 'test20@test.com',
	},
	createUserGoodPayload: {
		first_name: 'bruce',
		last_name: 'joe',
		role: 'Employee',
		password: 'Hello123321+_',
		passwordConfirmation: 'Hello123321+_+',
		email: 'test20@test.com',
		verified: false,
	},
	createUserBadPayload: {
		first_name: 'bruce',
		last_name: 'joe',
		role: 'Employee',
		password: 'Hello123321+_',
		passwordConfirmation: 'Hello123321+_+',
		email: 'test20@test.com',
		verified: false,
	},
	updateUserGoodPayload: {
		first_name: 'bruce',
		last_name: 'joe',
		role: 'Employee',
		password: 'Hello123321+_',
		passwordConfirmation: 'Hello123321+_',
		email: 'test20@test.com',
	},
	updateUserBadPayload: {
		first_name: 'bruce',
		last_name: 'joe',
		role: 'Employee',
		password: 'Hello123321+_',
		passwordConfirmation: 'Hello123321+_+',
		email: 'test20@test.com',
	},
};
